require 'rails_helper'

RSpec.describe 'AccessShortenedUrls', type: :system do
  before do
    driven_by(:rack_test)
  end

  before(:example) do
    @user = User.create(email: 'test@example.com', password: '123456')
    @url1 = @user.urls.create(full_url: 'http://example.com')
    @url2 = Url.create(full_url: 'http://example.com')
  end

  it "can't show a url generated by an authenticated user" do
    visit url_path(@url1)
    expect(page).to have_text("Link doesn't exist")
  end

  it 'show a url generated by an unauthenticated user' do
    visit url_path(@url2)
    expect(page).to have_text(@url2.full_url)
  end

  it 'show a url if generated by logged in user' do
    sign_in @user
    visit url_path(@url1)
    expect(page).to have_text(@url1.full_url)
  end

  it 'delete a url if generated by logged in user' do
    sign_in @user
    visit url_path(@url1)
    click_link_or_button 'Delete Link'
    expect(page).to have_text('Link deleted successfully.')
  end

  it 'delete a url generated by unauthenticated user' do
    visit url_path(@url2)
    click_link_or_button 'Delete Link'
    expect(page).to have_text('Link deleted successfully.')
  end
end
